### ISSUE TITLE
[validation] validate policies in Kustomize resources 

### ISSUE THREAD

**Issue by WitoDelnat** [kubeshop/monokle#1695]
Currently policy validation skips resources that are used within a Kustomization file. The difficulty is that these resources can be partial due to patches.

Let's illustrate with an example:

```
# demo-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      name: demo
    spec:        
      containers:
        - name: server
           image: nginx-ingres:v2.0
```

And a patch:

```
# demo-patch-cpu
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      name: demo
    spec:        
      containers:
        - name: server
           resources:
            limits:
              cpu: "150m"
```

If a Kustomization file puts these together then our editor will incorrectly say that the CPU limit is missing in the first example.

One idea is to show validation within a preview. The challenge will be to give actionable help. The preview is readonly and it's difficult to tell the file from which it originated. We can show the errors in the editor on the file that contains the resource that is not a patch. The idea is that once the validation errors are in SARIF format we can use the `relatedLocations` for this to allow Monaco to redirect to this page from within a preview.
