### ISSUE TITLE
Fail to `load` even when cluster is already connected

### ISSUE THREAD

**Issue by webup** [kubeshop/monokle#1855]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2936504/170727922-e1ee9067-c0d7-4a56-b66f-6a5b16b6b7c2.png)

The structure of `kubeconfig` file used looks like below, and it works well with `kubectl` or `k9s` cli tools:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: https://10.0.169.20:6443
  name: local
contexts:
- context:
    cluster: local
    namespace: default
    user: hailiz
  name: hailiz@local
current-context: hailiz@local
kind: Config
preferences: {}
users:
- name: hailiz
  user:
    client-certificate-data: 
    client-key-data: 
```

And the `client-certificate-data` is in pem format which has `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----` header/footer when decoded.

**Expected behavior**
Hope the load action works.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1
 - Version: 1.7.5 (tested on 1.7.x)

**Additional context**
Have also reported this issue in discord `bug-reports` channel.
