### ISSUE TITLE
Store a preferred version in the setting, and allow the user to select another version during one session

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#3058]
As a user, I want to be able to select a version of K8s schema to test without having to change the setting for it for later.

* it must be possible to change the preferred version, so every time I start a session the version is the one configured.
* it must be possible to change the version for this session without modyfing the preferred version
* it should be possible to identify the preferred version and go back to it.
* it should be possible to identify other versions used in external sources (i.e. the cluster k8s schema version)
* it should be possible to quickly deactivate the K8s schema validation
* it should be possible to compare the list of errors between two different schema versions in compare and sync.

For instance:
- My configuration files are being tested against K8s 1.25.2, that is my preferred version. Every time I start the session the version is that one.
- I want to connect to a cluster. When I do, the version in the cluster is 1.24.8. I don't want to see validation errors because of the mismatch in the cluster. When I connect, Monokle asks me if I want to change the session version to 1.24.8 or keep the same one.
- I want to be able to promote the session version to the settings one.
- I want to test if my cluster will have a problem if I update my cluster to 1.26.1. I select the version for the session and I see the changes.

**Comment by cerebro31** [comment]
Monokle is not showing a validation error when the Kubernetes schema version is changed.
Here is the sample manifest: 
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```
this `apiversion` is deprecated. When we deploy, Monokle is throwing error but not pre-deployment when validation is enabled.


https://user-images.githubusercontent.com/125909758/226903301-211ee7bb-a5ba-4fb2-9051-b42149c515fb.mp4
