### ISSUE TITLE
When changing the version of Kubernetes, there should be an error if the apiVersion is not supported

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#3542]
When I change the version of Kubernetes, I expect an error  if some apiVersion of a Kind is not supported and a warning if it is deprecated, so I don't have an error when I deploy to the cluster.

- Ideally, it should be possible to fix the problem automatically, but configuration files can change when moving from one version to another.

**Comment by cerebro31** [comment]
For version 1.25, cronjob is no longer [served](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125)
So Monokle Desktop should show a validation error but currently, there are no validation errors regarding Kubernetes Schema for this deprecated API.
![error_version_125](https://user-images.githubusercontent.com/125909758/228179964-b30958ad-3062-461b-b6c3-88f65eb322fd.png)

Here is the manifest for which i tested.
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```
