### ISSUE TITLE
Monokle thinks container is running with a low user/group ID

### ISSUE THREAD

**Issue by UntouchedWagons** [kubeshop/monokle#3663]
**Describe the bug**
The linter thinks that my container is running with a low user/group ID

**To Reproduce**
```
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bazarr
  namespace: default
  labels:
    app: bazarr
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      securityContext:
        runAsUser: 30000
        runAsGroup: 30000
        fsGroup: 30000
      containers:
        - name: bazarr
          image: truecharts/bazarr:1.2.0
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
```

**Expected behavior**
No linter issues

**Screenshots**
![pr1g6eqpYp](https://user-images.githubusercontent.com/160996/230633419-4ade10b4-0546-460b-994e-7478490c56df.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 Pro

**Additional context**
If I run `id` in a shell in the pod it says `uid=30000 gid=30000 groups=30000` so the container is definitely not running with a low user/group ID. I have the security context at the pod level so that the Longhorn volume used for config storage has the right permissions.

**Comment by erdkse** [comment]
thank you @UntouchedWagons for reporting this one. 

the `securityContext` should be a member of a `container` definition, so if you change your resource definition as follows you will see that the warning will be gone.

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bazarr
  namespace: default
  labels:
    app: bazarr
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
        - name: bazarr
          image: truecharts/bazarr:1.2.0
          securityContext:
          runAsUser: 30000
          runAsGroup: 30000
          fsGroup: 30000
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
```
