### ISSUE TITLE
Support kustomization schema from the kustomize cli (differs from kubectl kustomize?)

### ISSUE THREAD

**Issue by ngauje** [kubeshop/monokle#534]
**Describe the bug**
We use the `kustomize` cli to manage our configuration and not the `kubectl kustomize`. It looks like the kutomization.yaml schema supported differs between the 2. Maybe some parameters are not recognized by `kubectl kustomize`.

**To Reproduce**
Define a configmap generator or a secret generator with the `envs` parameter (to define source files to create a configmap) :
```
configMapGenerator:
- behavior: merge
  envs:
  - component1-vars.env
  - component2-vars.env
  name: app-env
```
Clic on preview

**Expected behavior**
A preview that work

**Error screenshot**
![image](https://user-images.githubusercontent.com/28781255/137633119-e2a47ffc-b6c8-4566-9720-47caf45bf2ad.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.2.2

**Additional context**
Check the kustomization reference : 
https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/configmapgenerator/
It support the `envs` parameter.
