### ISSUE TITLE
Ensure restricted access is handled gracefully

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#978]
Monokle currently expects cluster connections to have full access to a target cluster - need to make sure that restricted access in regard to namespaces/read/write/list/delete is handled gracefully also

**Comment by fog1985** [comment]
Hi @olensmar ,
I have created a service account inside of `monokle-rbac-testing` on testkube-dev GKE.
```
(base) taras.z.klym@lwo1-lmc-A03935:~/WORK/kubeshop/serviceaccount_creation $ kubectl --kubeconfig ./monokle-rbac-testing.config get pods
NAME    READY   STATUS    RESTARTS   AGE
nginx   1/1     Running   0          7s

(base) taras.z.klym@lwo1-lmc-A03935:~/WORK/kubeshop/serviceaccount_creation $ kubectl --kubeconfig ./monokle-rbac-testing.config delete pods nginx
Error from server (Forbidden): pods "nginx" is forbidden: User "system:serviceaccount:monokle-rbac-testing:monokle-test-serviceaccount" cannot delete resource "pods" in API group "" in the namespace "monokle-rbac-testing"
```
Will provide kube-config separately. App using this config will have these permissions:
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: monokle-rbac-testing
  name: monokle-test-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "secrets"]
  verbs: ["get", "watch", "list"]
```
If you will need more or different ones for the testing please let me know.
